augmentation:
  degrees: 10.0
  flip_lr: 0.5
  hsv_h: 0.015
  hsv_s: 0.7
  hsv_v: 0.4
  mosaic: 1.0
  scale: 0.5
  translate: 0.1
data:
  class_names: [] 
  num_classes: 8
  train_images: E:\dataset\VEDAI\vedai_8_double\images\visible\train
  train_labels: E:\dataset\VEDAI\vedai_8_double\labels\visible\train
  val_images: E:\dataset\VEDAI\vedai_8_double\images\visible\val
  val_labels: E:\dataset\VEDAI\vedai_8_double\labels\visible\val
eval:
  conf_threshold: 0.25   # 置信度阈值
  iou_threshold: 0.5    # mAP计算IoU阈值
  nms_threshold: 0.45    # NMS IoU阈值
loss:
  lambda_box: 7.5
  lambda_cls: 0.5
  lambda_dfl: 1.5
model:
  backbone: cspdarknet_s  # resnet18, resnet34, resnet50, cspdarknet_n, cspdarknet_s, cspdarknet_m
  input_size:
  - 640
  - 640
  num_anchors: 1    # Anchor-Free模式下设为1 (每个网格预测一个框)
optimizer:
  lr_schedule: cosine
  type: SGD
train:
  batch_size: 16
  checkpoint_dir: checkpoints_vedai_8
  epochs: 200
  learning_rate: 0.01
  momentum: 0.937
  num_workers: 4
  resume: ''
  save_interval: 10   # 保存间隔（以epoch为单位）
  warmup_epochs: 3
  weight_decay: 0.0005
